<?php
// beiwo2podcast
// https://github.com/Jamesits/beiwo2podcast
// Author: James Swineson
require_once('Curl/Curl.php');
// require_once('Curl/MultiCurl.php');
use \Curl\Curl;
header('charset=utf-8');
$version = '1.0';

// configuration
$default_limit = 15;
// $userid = '543a7790e4b06297c60d6ef9';
// $limit = 15;
if (!isset($_GET['id']))
    die('错误：缺少用户 ID');
$userid = $_GET['id'];
$limit = (isset($_GET['limit']) && intval($_GET['limit']) > 0) ? intval($_GET['limit']) : $default_limit;
$explicit = isset($_GET['explicit'])? $_GET['explicit'] : 'clean';
$category = isset($_GET['category'])? $_GET['category'] : 'Arts';
$subcategory = isset($_GET['subcategory'])? $_GET['subcategory'] : 'Performing Arts';

// get all useful metadata
$curl = new Curl();
$curl->setUserAgent('beiwo2podcast/'.$version);
$curl->setOpt(CURLOPT_ENCODING , 'gzip');

$curl->get('http://www.beiwo.ac/users/myPageDataWithPaging', array(
    'id' => $userid,
    'limit' => $limit,
    'curItems' => 0,
));
if ($curl->error) {
    die('错误 ' . $curl->error_code . '：' . $curl->error_message);
}
$listdata = json_decode($curl->response, true);
$episodes = $listdata['items'];

$curl->get('http://www.beiwo.ac/users/getSoundByIdWithAjax', array(
    'id' => $episodes[0]['objectId'],
    'code' => 0,
));
if ($curl->error) {
    die('错误 ' . $curl->error_code . '：' . $curl->error_message);
}
$songdata0 = json_decode($curl->response, true);
$userdata = $songdata0['user'];

// feed metadata vars
$feed_title = $userdata['nickName'].' - 被窝声次元';
$feed_link = "http://www.beiwo.ac/users/my?id=".$userid;
$feed_description = $userdata['nickName']."
".$userdata['mark']."

由 beiwo2podcast v".$version.' 自动生成。
https://github.com/Jamesits/beiwo2podcast';
$feed_copyright = 'Copyright 2014-'.date("Y").' beiwo.ac Inc. All rights reserved.';
$feed_ttl = 60 * 60 * 24;
$feed_lang = "zh-cn";

// iTunes specific metadata vars
$feed_author = $userdata['nickName'];
$feed_email = $userdata['email'];
$feed_image = $userdata['photo']['_url'];
$feed_explicit = $explicit;
$feed_category = $category;
$feed_subcategory = $subcategory;

// start output XML
header('Content-Type: application/xml; charset=utf-8');
echo '<?xml version="1.0" encoding="utf-8" ?>';
?>
<!-- generator="awesome-sauce/1.1" -->
<!--
Auto generated by beiwo2podcast v<?php echo $version; ?>
https://github.com/Jamesits/beiwo2podcast
-->
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">

    <channel>
        <title><?php echo $feed_title; ?></title>
        <link><?php echo $feed_link; ?></link>

        <itunes:author><?php echo $feed_author; ?></itunes:author>
        <itunes:owner>
            <itunes:name><?php echo $feed_author; ?></itunes:name>
            <itunes:email><?php echo $feed_email; ?></itunes:email>
        </itunes:owner>

        <itunes:image href="<?php echo $feed_image; ?>" />
        <itunes:explicit><?php echo $feed_explicit; ?></itunes:explicit>
        <itunes:category text="<?php echo $feed_category; ?>">
            <itunes:category text="<?php echo $feed_subcategory; ?>" />
        </itunes:category>

        <itunes:summary><?php printf($feed_description); ?></itunes:summary>

        <category>Music</category>
        <description><?php echo printf($feed_description); ?></description>

        <language><?php echo $feed_lang; ?></language>
        <copyright><?php echo $feed_copyright; ?></copyright>
        <ttl><?php echo $feed_ttl; ?></ttl>

        <?php
        foreach ($episodes as $e) {
                $title = $e['title'];
                $url = $e['sound']['url'];
                $author = $feed_author;
                $duration = $e['length'];
                $description = $e['content'];
                $date = date(DateTime::RFC2822, strtotime($e['createdAt']));
                $size = $e['size'];
        ?>
        <item>
            <title><?php echo $title; ?></title>
            <link><?php echo $url; ?></link>

            <itunes:author><?php echo $author; ?></itunes:author>
            <itunes:category text="<?php echo $feed_category; ?>">
                <itunes:category text="<?php echo $feed_subcategory; ?>" />
            </itunes:category>

            <category>Music</category>
            <duration><?php echo $duration; ?></duration>

            <description><?php printf($description); ?></description>
            <pubDate><?php echo $date; ?></pubDate>

            <enclosure url="<?php echo $url; ?>" length="<?php echo $size; ?>" type="audio/mpeg" />
            <guid><?php echo $url; ?></guid>
            <author><?php echo $feed_email; ?></author>
        </item>
        <?php
        }
        ?>

    </channel>
</rss>
